# Generated by Django 5.2.4 on 2025-10-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_user_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='IT_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='accounts_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='housing_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='last_working_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='remarks_IT',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='remarks_accounts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='remarks_housing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='remarks_store',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='remarks_workshop',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='store_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='workshop_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
