# Generated by Django 5.2.4 on 2025-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_application_it_status_application_accounts_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='from_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='to_date',
            field=models.DateField(blank=True),
        ),
    ]
