# Generated by Django 5.2.4 on 2025-10-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_application_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
