# Generated by Django 5.2.4 on 2025-07-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('it_code', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('signature_employee', models.CharField(blank=True, max_length=255)),
                ('signature_it', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.user')),
                ('inventory_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.inventoryitem')),
            ],
        ),
    ]
