# Generated by Django 5.2.4 on 2025-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_inventoryitem_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='signature_it',
            new_name='signature_head',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='it_code',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='asset_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='buy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
