# Generated by Django 5.2.4 on 2025-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_signature_it_inventory_signature_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='signature_employee',
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_status',
            field=models.IntegerField(choices=[(1, 'Issued'), (2, 'Returned'), (3, 'Lost')], default=1),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
