# Generated by Django 5.2.4 on 2025-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_inventory_signature_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
