# Generated by Django 5.2.4 on 2025-07-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_inventory_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Inventory Report',
                'verbose_name_plural': 'Inventory Report',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='signature_head',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
