# Generated by Django 5.2.4 on 2025-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='application',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
