# Generated by Django 5.2.4 on 2025-08-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
