# Generated by Django 5.2.4 on 2025-08-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_application_entry_date_user_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='delete_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], default=None, max_length=10, null=True),
        ),
    ]
