# Generated by Django 5.2.4 on 2025-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_application_delete_status_alter_user_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='remarks_dep_head',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='remarks_gm',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='remarks_hr',
            field=models.TextField(blank=True),
        ),
    ]
