# Generated by Django 5.2.4 on 2025-08-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_application_dep_head_status_application_gm_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
