# Generated by Django 5.2.4 on 2025-08-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_application_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
