# Generated by Django 5.2.4 on 2025-08-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_inventoryitem_inventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
