# Generated by Django 5.2.4 on 2025-08-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_remove_departmenthead_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
