# Generated by Django 5.2.4 on 2025-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_alter_user_batch_number_alter_user_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
