# Generated by Django 5.2.4 on 2025-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_user_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
